### ISSUE TITLE
[SUGGESTION] Add Social Media Links to the Player settings

### ISSUE THREAD

**Issue by PhoenixGames-Phoenix** [Bregann/Hypixel.NET#13]
Currently, in Hypixel.NET there is no way to get the Social Media Links that players can set in their Hypixel Profile

My Suggestion is, to add the different Social Media Links to the Player class like this:
`HypixelApi api = new HypixelApi(Token, 300) 
var user = await api.GetUserByPlayerNameAsync(username).ConfigureAwait(false)
string discord = user.Player.Settings.SocialMedia.Discord
`

This would be very useful for me because then i could easily automate verifying that people on my discord server own their Minecraft Account with the discord bot i wrote

**Comment by Bregann** [comment]
Yeah I'll get those added

**Comment by artu165** [comment]
I've added the requested suggestion on this pull request: #14 Just needs to be merged and you'll be able to implement it on your Discord bot by doing the following:

`var user = await hypixel.GetUserByPlayerNameAsync(USERNAME).ConfigureAwait(false);
Console.WriteLine(user.Player.SocialMedia.Links.Discord)`

**Comment by Bregann** [comment]
it'll be added this weekend

**Comment by Bregann** [comment]
package will be live shortly
