### ISSUE TITLE
[SUGGESTION] Throw an exception when creating a HypixelApi object with an invalid key

### ISSUE THREAD

**Issue by iwillreku3206** [Bregann/Hypixel.NET#6]
Normally, creating a HypixelApi object with an invalid key would still work:
`HypixelApi hypixel = new HypixelApi("<invalid key here>", 300);`

It is only when making requests with this Hypixel Api object that an exception is thrown:
`HypixelApi hypixel = new HypixelApi("<invalid key here>", 300);
Console.WriteLine(hypixel.GetAuctionPage(0).WasSuccessful);` <- Exception is here

My suggestion is that the exception is thrown in the 1st line of code above:
`HypixelApi hypixel = new HypixelApi("<invalid key here>", 300);` <- Exception here
`Console.WriteLine(hypixel.GetAuctionPage(0).WasSuccessful);`

This may be helpful when I write programs that use the user's API key to see if it is valid.

**Comment by Bregann** [comment]
Cool idea - I'll look into this

**Comment by Bregann** [comment]
new package will be up at https://www.nuget.org/packages/Hypixel.NET/ shortly
