### ISSUE TITLE
[SUGGESTION] Add support for queriesInPastMinute

### ISSUE THREAD

**Issue by iwillreku3206** [Bregann/Hypixel.NET#7]
Currently, in Hypixel.NET, the queriesInPastMinute seen in the Hypixel public API is not present. 

In the Hypixel API key information (accessible by doing a GET request at `https://api.hypixel.net/key?key=<API key>`, there is an integer showing the number of queries made to the API by the given key in the past minute.

This may be useful in writing programs that use the API while ensuring that the key given is not overused

**Comment by Bregann** [comment]
Will add this one

**Comment by Bregann** [comment]
new package will be up at https://www.nuget.org/packages/Hypixel.NET/ shortly
